version: '3'
services:
  app: 
    image: mcr.microsoft.com/devcontainers/anaconda:0-3
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    # https://goledger.medium.com/reaching-hosts-localhost-from-inside-a-vscode-devcontainer-932e1c08df5c
    networks:
      - database

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lander@vanderstighelen.net
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - database

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - database

volumes:
  postgres-data:

networks:
  database:
    driver: bridge